version: '3'

volumes:
  housekeeping-volume:

networks:
  housekeeping-network:

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - 5432:5432
    networks:
      - housekeeping-network

