version: '3'

volumes:
  housekeeping-volume:

networks:
  housekeeping-network:

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres_secret
      POSTGRES_DB: housekeeping-db
      POSTGRES_USER: housekeeping-db-admin
    ports:
      - 5432:5432
    networks:
      - housekeeping-network
